# Generated by Django 2.2.14 on 2020-07-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FectchBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('due_amount', models.FloatField()),
                ('ref_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
