# Generated by Django 2.2.14 on 2020-07-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setuApp', '0002_fectchbill_mobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FectchBill',
            new_name='FetchBill',
        ),
    ]
